match(
      type: "appstore",
      api_key: api_key
    )

    profile_name = lane_context[SharedValues::MATCH_PROVISIONING_PROFILE_MAPPING]["com.forsa-quran"]

    update_code_signing_settings(
      use_automatic_signing: false,
      path: "forsa_quran.xcodeproj",
      code_sign_identity: "Apple Distribution",
      bundle_identifier: "com.forsa-quran",
      profile_name: profile_name,
      team_id: ENV["APPLE_TEAM_ID"]
    )

    build_app(scheme: "forsa_quran")

    upload_to_testflight(
      api_key: api_key
    )