# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :custom_lane do
    # add actions here: https://docs.fastlane.tools/actions
  end

  desc "Build and upload a release build to TestFlight"
  lane :release do
    api_key = app_store_connect_api_key(
      key_id: ENV["APP_STORE_CONNECT_KEY_ID"],
      issuer_id: ENV["APP_STORE_CONNECT_ISSUER_ID"],
      key_content: ENV["APP_STORE_CONNECT_KEY_CONTENT"],
      is_key_content_base64: false
    )

    match(
      type: "appstore",
      api_key: api_key
    )

    update_code_signing_settings(
      use_automatic_signing: false,
      path: "forsa_quran.xcodeproj",
      code_sign_identity: "Apple Distribution",
      bundle_identifier: "com.forsa-quran",
      profile_name: "match AppStore com.forsa-quran",
      team_id: ENV["APPLE_TEAM_ID"]
    )

    build_app(scheme: "forsa_quran")

    upload_to_testflight(
      api_key: api_key
    )
  end
end