desc "Build and upload a release build to TestFlight"
  lane :release do
    api_key = app_store_connect_api_key(
      key_id: ENV["APP_STORE_CONNECT_KEY_ID"],
      issuer_id: ENV["APP_STORE_CONNECT_ISSUER_ID"],
      key_content: ENV["APP_STORE_CONNECT_KEY_CONTENT"],
      is_key_content_base64: false
    )

    match(
      type: "appstore",
      api_key: api_key
    )

    update_code_signing_settings(
      use_automatic_signing: false,
      path: "forsa_quran.xcodeproj",
      code_sign_identity: "Apple Distribution",
      bundle_identifier: "com.forsa-quran",
      profile_name: ENV["SIGH_PROFILE_NAME"],
      team_id: ENV["APPLE_TEAM_ID"]
    )

    build_app(scheme: "forsa_quran")

    upload_to_testflight(
      api_key: api_key
    )
  end